version: 0.2

env:
  variables:
    ECR_REPO: "640168412115.dkr.ecr.us-east-1.amazonaws.com/simple-docker-service-0afff1e6c27f"

phases:
  install:
    commands:
      - echo "Checking Docker version..."
      - docker --version
      - echo "Environment setup complete."

  pre_build:
    commands:
      - echo "Logging into AWS ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO:latest -f Dockerfile .

      - echo "Tagging Docker image..."
      - docker tag $ECR_REPO:latest $ECR_REPO:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO:latest
      - echo "Build and push completed successfully!"

artifacts:
  files:
    - '**/*'
