version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into AWS ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 640168412115.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Pulling the latest Docker image..."
      - docker pull 640168412115.dkr.ecr.us-east-1.amazonaws.com/ecr-rds-repository:latest1
      - echo "Creating a container from the image..."
      - CONTAINER_ID=$(docker create 640168412115.dkr.ecr.us-east-1.amazonaws.com/ecr-rds-repository:latest1)
      - echo "Copying files from the container..."
      - docker cp $CONTAINER_ID:/var/www/app ./app-output  # Change this path accordingly
      - 
      - echo "Zipping extracted files..."
      - zip -r app.zip ./app-output
  post_build:
    commands:
      - echo "Uploading built files to S3..."
      - aws s3 cp app.zip s3://pull-dockerimage/app.zip

artifacts:
  files:
    - app.zip
